baseURL = "https://nacharya.github.io"
languageCode = "en-us"
title = "Nabin Acharya"
theme = "hugo-coder"
defaultcontentlanguage = "en"
paginate = 20
canonifyurls = true
enableEmoji = true
enableRobotsTXT = true

#pygmentsstyle = "monokai"
#pygmentscodefences = false
#pygmentscodefencesguesssyntax = true
#pygmentsUseClasses = true

# Enable Disqus
#disqusShortname = ""
# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
author = "Nabin Acharya"
info = "Data Engineering, Data Science, Software Products & Architecture"
description = "Sailing pirate ships for fun"
#keywords = "blog,data,iiot,fintech, software architecture"
keywords = ""
avatarurl = "images/nacharya.jpg"
dateFormat = "January 2, 2006"
since = 2019
favicon = "favicons/"
footercontent = ""
colorscheme = "auto"
hidecredits = false
hidecopyright = false
rtl = false
math = true
custom_css = ["css/custom.css"]
custom_scss = ["scss/custom.scss"]
custom_js = ["js/custom.js"]
doNotLoadAnimations = false


[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-dark"
    tabWidth = 4

[[params.social]]
    title = "Github"
    icon = "fa fa-github fa-2x"
	url   = "https://github.com/nacharya"
	weight = 1
[[params.social]]
    title = "e-mail"
	icon = "fa fa-envelope fa-2x"
	url          = "mailto:nabin.acharya@gmail.com"
	weight = 2
[[params.social]]
    title = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
	url       = "https://www.linkedin.com/in/nabinacharya"
	weight = 3

# Menu links
[menu]
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 3
    url  = "/posts/"
[[menu.main]]
    name = "Research"
    weight = 2
    url  = "/research/"
[[menu.main]]
    name = "Projects"
    weight = 4
    url  = "/projects/"
