baseURL = "https://nacharya.github.io"
languageCode = "en-us"
title = "Nabin Acharya"
theme = "hugo-coder"

defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

# pygmentsstyle = "monokai"
# pygmentscodefences = false
# pygmentscodefencesguesssyntax = true
# pygmentsUseClasses = true

[params]
    author = "Nabin Acharya"
    info = "Data Engineering, Data Science, Software Products & Architecture"
	description = "Sailing pirate ships for fun"
	#keywords = "blog,data,iiot,fintech, software architecture"
    keywords = ""
    avatarurl = "images/nacharya.jpg"
	favicon = "favicons/"

    footercontent = ""
    colorscheme = "light"

    hidecredits = false
    hidecopyright = false
    
	rtl = false
    math = true
   
   	custom_css = ["css/custom.css"]
	customJs = []
	doNotLoadAnimations = false


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-dark"
    tabWidth = 4

[[params.social]]
    title = "Github"
    icon = "fab fa-github fa-2x"
	url   = "https://github.com/nacharya"

[[params.social]]
    title = "e-mail"
	icon = "fas fa-envelope fa-2x"
	url          = "mailto:nabin.acharya@gmail.com"

[[params.social]]
    title = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
	url       = "https://www.linkedin.com/in/nabinacharya"

# Menu links
[menu]
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 3
    url  = "/posts/"
[[menu.main]]
    name = "Research"
    weight = 2
    url  = "/research/"
[[menu.main]]
    name = "Photos"
    weight = 6
    url  = "/photography/"
[[menu.main]]
    name = "Projects"
    weight = 4
    url  = "/projects/"
[[menu.main]]
    name = "Hobbies"
    weight = 4
    url  = "/hobbies/"
